/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolhelp;

//Library yang digunkaan dalam program ini
import java.util.ArrayList;
import javax.swing.JOptionPane;
import MyClass.Volunteer;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author meone
 */
public class regisForm extends javax.swing.JFrame {

    /**
     * Creates new form regisForm
     */
    //ArrayList untuk menyimpan data dari Volunteer
    ArrayList<Volunteer> v;
    
    public regisForm() {
        //Deklarasikan ArrayList
        v = new ArrayList<Volunteer>();
        
        initComponents();
        
        //PAnggil ArrayList
        regisArrayList();
    }
    
    //Fungsi ini untuk mengecek apakah Masih Ada JTExtField yang kosong apa tidak
    public boolean validateText(){
        if (vUser.getText().isEmpty() || vPass.getText().isEmpty() || vName.getText().isEmpty() ||
                vEmail.getText().isEmpty() || vTelepon.getText().isEmpty() || vJob.getText().isEmpty() || vDate.getDate().equals(null)){
            JOptionPane.showMessageDialog(null, "Tolong Diisi Semua!", "Failed Login", 2);
            return false;
        }else if ( vDate.getDate().compareTo(new Date()) > 0){
            JOptionPane.showMessageDialog(null, "Tolong isi Tanggal lahir dengan Benar");
            return false;
        }else{
            return true;
        }
    }
    
    //fungsi ini berguna untuk menyimpan data yang telah kita input pada arraylist ke dalam file.data
    public void savetoFile(){
        
        try{
            
            FileOutputStream file = new FileOutputStream("regis.dat");
            ObjectOutputStream outputfile = new ObjectOutputStream(file);
            
            for (int i = 0; i < v.size(); i++){
                outputfile.writeObject(v.get(i));
            }
            
            outputfile.close();
            
            JOptionPane.showMessageDialog(null, "Successfully Register!!");
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }   
    }
    
    //Fungsi ini berguna untuk membaca isi dari file.data dan didsimpan didalam arrayList
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("regis.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    v.add((Volunteer) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        
    }
    
    //Fungsi ini berguna agar username yang kita daftarkan tidak terdaftar 2x
    public boolean cekUsername(String Username){
        boolean cek = false;
        try{
            
            for (int i = 0; i < v.size(); i++){
                if ( Username.equals(v.get(i).getUsername()) ){
                    cek = true;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return cek;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vUser = new javax.swing.JTextField();
        vPass = new javax.swing.JPasswordField();
        RegisButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vName = new javax.swing.JTextField();
        vTelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vJob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        vDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        vEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/School.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("School HELP");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register Volunteer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 600, 100));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        vUser.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(vUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 360, -1));

        vPass.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jPanel1.add(vPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 360, -1));

        RegisButton.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        RegisButton.setText("Register");
        RegisButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegisButton.setContentAreaFilled(false);
        RegisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 100, 30));

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Masuk Disini!");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 600, 40));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel7.setText("Nama Lengkap");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        vName.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(vName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 360, -1));

        vTelepon.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(vTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 360, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel8.setText("Telepon");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel9.setText("Tanggal Lahir");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        vJob.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(vJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 360, -1));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel10.setText("Pekerjaan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        vDate.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jPanel1.add(vDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 360, 30));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        vEmail.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(vEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Fungsi ini terjadi jika kita mengklik tombol regis
    private void RegisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisButtonActionPerformed
        // Mengecek apakah sudah terisi semua data yang ada
        
        if(validateText()){
            //ambil semua data yang telah kita isikan disimpan kedalam variable baru
            String user = vUser.getText().trim();
            String Pass = vPass.getText().trim();
            String Name = vName.getText().trim();
            String email = vEmail.getText().trim();
            String Telepon = vTelepon.getText().trim();
            String Job = vJob.getText().trim();
            
            //ini berguna untuk memformat JDateChooser (Tanggal) menjadi tahun-bulan-hari
            //Lalu diubah menjadi String
            SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
            String Date = dt.format(vDate.getDate());
            
            //simpan kedalam varibael cek dari fungsi cekUsername
            boolean cek = cekUsername(user);
            
            //apabila mengembalikan nilai true maka username yang kita daftarkan harus diganti 
            //sebab telah ada yang menggunakannya
            if (cek){
                JOptionPane.showMessageDialog(null, Name + " Telah Digunakan, Silahkan Coba yang lain!");
            }else{
                //jika tidak maka panggil contructor dari class Volunter dan simpan semua variabel
                Volunteer vt = new Volunteer(Date, Job, user, Pass, Name, email, Telepon);
                
                //lalu add ke dalam array list
                v.add(vt);
                
                //dan simpan kedalam file.dat
                savetoFile();
            }
        }
        
    }//GEN-LAST:event_RegisButtonActionPerformed

    //fungsi ini berguna untuk kembali ke halaman login
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser vDate;
    private javax.swing.JTextField vEmail;
    private javax.swing.JTextField vJob;
    private javax.swing.JTextField vName;
    private javax.swing.JPasswordField vPass;
    private javax.swing.JTextField vTelepon;
    private javax.swing.JTextField vUser;
    // End of variables declaration//GEN-END:variables
}
