/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolhelp;
import MyClass.*;
import java.io.*;
import java.util.*;
import java.util.Random;
import java.util.UUID;
import javax.swing.JOptionPane;
/**
 *
 * @author meone
 */
public class SchoolHELPAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SchoolHELPAdmin
     */
    //Buat array list untuk menyimpan data school
    ArrayList<School> s;
    String Id;
    public SchoolHELPAdmin() {
        //fungsi ini untuk ngeset location relative frame menjadi null
        setLocationRelativeTo(null);
        
        //deklarsikan array list school
        s = new ArrayList<School>();
        initComponents();
        
        //buat SchoolID Otomatis
        Random rand = new Random();
        Id = "SCH" + String.format("%03d", rand.nextInt(1000));
        sID.setText(Id);
        
        //panggil regisArrayList
        regisArrayList();
    }
    
    //fungsi untuk menampilkan nama user di sudut kiri atas dari form
    public void Display(String nama){
        NamaDisplay.setText(nama);
    }
    
    //fungsi untuk menyimpan data ke dalam file.dat dari arraylist
    public void savetoFile(){
        
        try{
            
            FileOutputStream file = new FileOutputStream("school.dat");
            ObjectOutputStream outputfile = new ObjectOutputStream(file);
            
            for (int i = 0; i < s.size(); i++){
                outputfile.writeObject(s.get(i));
            }
            
            outputfile.close();
            
            JOptionPane.showMessageDialog(null, "Successfully Register!!");
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Salah Disini!");
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    //fungsi untuk membaca file.data dan disimpan kedalam array list
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("school.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    s.add((School) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    //fungsi untuk mengecek apakah semua jtextfield telah terisi semua atau tidak
    public boolean validateText(){
        if (sName.getText().isEmpty() || sAddress.getText().isEmpty() || sCity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tolong Diisi Semua!", "Failed Login", 2);
            return false;
        }else{
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LogOut = new javax.swing.JButton();
        School = new javax.swing.JButton();
        Schooladmin1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NamaDisplay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sCity = new javax.swing.JTextField();
        sAddress = new javax.swing.JTextField();
        sName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RegisButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        LogOut.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogOut.setContentAreaFilled(false);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 50));

        School.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        School.setText("School");
        School.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        School.setContentAreaFilled(false);
        jPanel2.add(School, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 50));

        Schooladmin1.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        Schooladmin1.setText("School Admin");
        Schooladmin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Schooladmin1.setContentAreaFilled(false);
        Schooladmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Schooladmin1ActionPerformed(evt);
            }
        });
        jPanel2.add(Schooladmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 600));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/School[Dashboard].png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel2.setText(" School HELP");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 250, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/UserProfile.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2, -1, 50));

        NamaDisplay.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NamaDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NamaDisplay.setText("jLabel4");
        jPanel3.add(NamaDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 300, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel7.setText("School Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel8.setText("School Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel10.setText("School City");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        sCity.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(sCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 360, -1));

        sAddress.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(sAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 360, -1));

        sName.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 360, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Register School");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 900, 100));

        RegisButton.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        RegisButton.setText("Register");
        RegisButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegisButton.setContentAreaFilled(false);
        RegisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 100, 30));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel9.setText("School ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        sID.setEditable(false);
        sID.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(sID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //fungsi bekerja setelah kita mengklik tombol log out maka akan kembali ke halaman login
    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        //dispose berna untuk mengclose halaman sebelumnya
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    //fungsi akan bekerja ketika kita klik regis button maka akan mendaftarkan sekolah yang telah kita isi
    private void RegisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisButtonActionPerformed
        // TODO add your handling code here:
        //cek apakah data sudah terisi semua atau tidak
        if (validateText()){
            //simpan semua data ke dalam variabel
            String idSchool = sID.getText().trim();
            String Name = sName.getText().trim();
            String Address = sAddress.getText().trim();
            String City = sCity.getText().trim();
            
            //panggil kontruktor school yang nanti nya akan disimpan ke dalam array list
            School S = new School(idSchool,Name, Address, City);
            s.add(S);
            
            //simpan object school ke dalam file.dat
            savetoFile();
        }
        
    }//GEN-LAST:event_RegisButtonActionPerformed

    //fungsi ini berfugnsi untuk menampilkan halaman daftar school admin
    private void Schooladmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schooladmin1ActionPerformed
        // TODO add your handling code here:
        SchoolHELPAdmin_2 sh2 = new SchoolHELPAdmin_2();
        sh2.setVisible(true);
        sh2.Display(NamaDisplay.getText());
        this.dispose();
    }//GEN-LAST:event_Schooladmin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolHELPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolHELPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolHELPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolHELPAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolHELPAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JLabel NamaDisplay;
    private javax.swing.JButton RegisButton;
    private javax.swing.JButton School;
    private javax.swing.JButton Schooladmin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField sAddress;
    private javax.swing.JTextField sCity;
    private javax.swing.JTextField sID;
    private javax.swing.JTextField sName;
    // End of variables declaration//GEN-END:variables
}
