/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolhelp;

import MyClass.*;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author meone
 */
public class SchoolAdmin_2 extends javax.swing.JFrame {

    /**
     * Creates new form SchoolAdmin_2
     */
    
    //Array List untuk menyimpan data dari resource request
    ArrayList<Resource> r;
    
    public SchoolAdmin_2() {
        //dekalarsikan arraylist resource 
        r = new ArrayList<Resource>();
        initComponents();
        
        //fungsi untuk membuat Id Request otomatis
        Random rand = new Random();
        String Id = "RR" + String.format("%03d", rand.nextInt(1000));
        rrID.setText(Id);
        
        //panggil fungsi regisArrayList()
        regisArrayList();
    }
    
    //Fungsi untuk menampilkan nama admin di sudutkiri atas dair form
    public void Display(String nama){
        NamaDisplay.setText(nama);
    }
    
    //fungsi untuuk menampilkan info dari school admin
    public void DisplayInfo(String nama, String Position, String id, String schoolName){
        NameAdmin.setText(nama);
        NamaDisplay.setText(nama);
        PositionAdmin.setText(Position);
        IdSchool.setText(id);
        SchoolNameAdmin.setText(schoolName);
    }
    
    //fungsi untuk cek data sudah terisi semua apa belum
    public boolean validateText(){
        if (rrID.getText().isEmpty() || rrReqDate.getDate().equals(null) || rrType.getText().isEmpty() || rrNum.getText().isEmpty() || rrDesc.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tolong Diisi Semua!", "Failed Login", 2);
            return false;
        }else{
            return true;
        }
    }
    
    //fungsi untuk menyimpan data yang ada pada arraylist ke dalam file.dat
    public void savetoFile(){
        
        try{
            
            FileOutputStream file = new FileOutputStream("resource.dat");
            ObjectOutputStream outputfile = new ObjectOutputStream(file);
            
            for (int i = 0; i < r.size(); i++){
                outputfile.writeObject(r.get(i));
            }
            
            outputfile.close();
            
            JOptionPane.showMessageDialog(null, "Successfully Saved!!");
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    //fungsi untuk menyimpan data ke dalam array list dari file.dat
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("resource.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    r.add((Resource) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NamaDisplay = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rrNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ajukan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        rrDesc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ReviewOffer = new javax.swing.JButton();
        Tutorial = new javax.swing.JButton();
        Resource = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        SchoolNameAdmin = new javax.swing.JLabel();
        NameAdmin = new javax.swing.JLabel();
        PositionAdmin = new javax.swing.JLabel();
        IdSchool = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rrReqDate = new com.toedter.calendar.JDateChooser();
        rrID = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        rrType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/School[Dashboard].png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel2.setText(" School HELP");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 250, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/UserProfile.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2, -1, 50));

        NamaDisplay.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NamaDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NamaDisplay.setText("jLabel4");
        jPanel3.add(NamaDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 300, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel10.setText("Num Required");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        rrNum.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(rrNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 400, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Resource Request");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 900, 100));

        Ajukan.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        Ajukan.setText("Ajukan");
        Ajukan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ajukan.setContentAreaFilled(false);
        Ajukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjukanActionPerformed(evt);
            }
        });
        jPanel1.add(Ajukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 100, 30));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel11.setText("Description");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        rrDesc.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(rrDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 400, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        ReviewOffer.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        ReviewOffer.setText("Review Offers");
        ReviewOffer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReviewOffer.setContentAreaFilled(false);
        ReviewOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewOfferActionPerformed(evt);
            }
        });
        jPanel2.add(ReviewOffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 50));

        Tutorial.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        Tutorial.setText("Tutorial ");
        Tutorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tutorial.setContentAreaFilled(false);
        Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialActionPerformed(evt);
            }
        });
        jPanel2.add(Tutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 50));

        Resource.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        Resource.setText("Resource");
        Resource.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Resource.setContentAreaFilled(false);
        Resource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourceActionPerformed(evt);
            }
        });
        jPanel2.add(Resource, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 300, 50));

        LogOut.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogOut.setContentAreaFilled(false);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 300, 50));

        SchoolNameAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        SchoolNameAdmin.setText("jLabel6");
        jPanel2.add(SchoolNameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, 30));

        NameAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NameAdmin.setText("jLabel6");
        jPanel2.add(NameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 30));

        PositionAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        PositionAdmin.setText("jLabel6");
        jPanel2.add(PositionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        IdSchool.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        IdSchool.setText("jLabel6");
        jPanel2.add(IdSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 600));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel9.setText("Request ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel14.setText("Request Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        rrReqDate.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jPanel1.add(rrReqDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 400, 30));

        rrID.setEditable(false);
        rrID.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(rrID, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 400, -1));

        Cancel.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel.setContentAreaFilled(false);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, 100, 30));

        jLabel13.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel13.setText("Resource Type");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        rrType.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(rrType, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //fungsi untuk ke halaman review offer
    private void ReviewOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewOfferActionPerformed
        // TODO add your handling code here:
        SchoolAdmin_3 sa3 = new SchoolAdmin_3();
        sa3.setVisible(true);
        sa3.Display(NamaDisplay.getText());
        sa3.DisplayInfo(NameAdmin.getText(), PositionAdmin.getText(), IdSchool.getText(), SchoolNameAdmin.getText());
        this.dispose();
    }//GEN-LAST:event_ReviewOfferActionPerformed

    //fungsi untuk merefresh halaman
    private void ResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourceActionPerformed
        // TODO add your handling code here:
        SchoolAdmin_2 sa = new SchoolAdmin_2();
        sa.setVisible(true);
        sa.Display(NamaDisplay.getText());
        sa.DisplayInfo(NameAdmin.getText(), PositionAdmin.getText(), IdSchool.getText(), SchoolNameAdmin.getText());
        this.dispose();
    }//GEN-LAST:event_ResourceActionPerformed

    //fungsi untuk log out atau kembali ke halaman login
    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    //fungsi untuk ke halaman tutorial request
    private void TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialActionPerformed
        SchoolAdmin_1 sa1 = new SchoolAdmin_1();
        sa1.setVisible(true);
        sa1.Display(NamaDisplay.getText());
        sa1.DisplayInfo(NameAdmin.getText(), PositionAdmin.getText(), IdSchool.getText(), SchoolNameAdmin.getText());
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TutorialActionPerformed

    //fungsi untuk mengjukan reqeust
    private void AjukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjukanActionPerformed
        // cek data sudah terisi semua atau belum
        if (validateText()){
            //fungsi untuk memformat tanggal dan cash ke string
            SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");

            String reqID = rrID.getText().trim();
            String Status = "PENDING";
            String ReqDate = dt.format(rrReqDate.getDate());
            String Type = rrType.getText().trim();
            String Num = rrNum.getText().trim();
            String Desc = rrDesc.getText().trim();
            String SchoolName = SchoolNameAdmin.getText();
            
            //panggil contructor dan simpan data
            Resource R = new Resource(SchoolName, Type, Num, reqID, ReqDate, Status, Desc);
            
            //simpan object resource ke dalam arraylist
            r.add(R);
            
            //fungsi untuk menyimpan object ke file.dat
            savetoFile();
        }
    }//GEN-LAST:event_AjukanActionPerformed

    //fungsi untuk membatalkan reqeust
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        rrID.setText("");
        rrReqDate.setDate(null);
        rrType.setText("");
        rrNum.setText("");
        rrDesc.setText("");
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolAdmin_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajukan;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel IdSchool;
    private javax.swing.JButton LogOut;
    private javax.swing.JLabel NamaDisplay;
    private javax.swing.JLabel NameAdmin;
    private javax.swing.JLabel PositionAdmin;
    private javax.swing.JButton Resource;
    private javax.swing.JButton ReviewOffer;
    private javax.swing.JLabel SchoolNameAdmin;
    private javax.swing.JButton Tutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField rrDesc;
    private javax.swing.JTextField rrID;
    private javax.swing.JTextField rrNum;
    private com.toedter.calendar.JDateChooser rrReqDate;
    private javax.swing.JTextField rrType;
    // End of variables declaration//GEN-END:variables
}
