/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolhelp;

import MyClass.*;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author meone
 */
public class SchoolAdmin_1 extends javax.swing.JFrame {

    /**
     * Creates new form SchoolAdmin_1
     */
    //Array list untuk menyimapan data dari tutorial reuqest
    ArrayList<Tutorial> t;
    
    public SchoolAdmin_1() {
        //deklarsikan array list
        t = new ArrayList<Tutorial>();
        initComponents();
        
        //fungsi untuk membuat id request secara otomatis
        Random rand = new Random();
        String Id = "TR" + String.format("%03d", rand.nextInt(1000));
        trID.setText(Id);
        
        //panggil fungsi regisArraylist
        regisArrayList();
    }
    
    //fugnsi untuk mendisplay nama admin school di sudut kiri atas dari form
    public void Display(String nama){
        NamaDisplay.setText(nama);
    }
    
    //fungsi untuk menampilkan info dari schooladmin 
    public void DisplayInfo(String nama, String Position, String id, String schoolName){
        NameAdmin.setText(nama);
        NamaDisplay.setText(nama);
        PositionAdmin.setText(Position);
        IdSchool.setText(id);
        SchoolNameAdmin.setText(schoolName);
    }
    
    //fungsi untuk ngecek apakah data reuqest sudah terisi semua atau belum
    public boolean validateText(){
        if (trID.getText().isEmpty() || trReqDate.getDate().equals(null) || trPDate.getDate().equals(null)
                || trTime.getText().isEmpty() || trLevel.getText().isEmpty() || trSum.getText().isEmpty() || trDesc.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tolong Diisi Semua!", "Failed Login", 2);
            return false;
        }else{
            return true;
        }
    }
    
    //fungsi untuk menyimpan data yang ada didalam arrayList ke dalam file.dat
    public void savetoFile(){
        
        try{
            
            FileOutputStream file = new FileOutputStream("tutorial.dat");
            ObjectOutputStream outputfile = new ObjectOutputStream(file);
            
            for (int i = 0; i < t.size(); i++){
                outputfile.writeObject(t.get(i));
            }
            
            outputfile.close();
            
            JOptionPane.showMessageDialog(null, "Successfully Saved!!");
            
        }catch(IOException e){
//            JOptionPane.showMessageDialog(null, "Salah Disini!");
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    //fungsi untuk membaca data dari file.dat dan akan disimpan kedalam arraylist
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("tutorial.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    t.add((Tutorial) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ReviewOffer = new javax.swing.JButton();
        Tutorial = new javax.swing.JButton();
        Resource = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        SchoolNameAdmin = new javax.swing.JLabel();
        NameAdmin = new javax.swing.JLabel();
        PositionAdmin = new javax.swing.JLabel();
        IdSchool = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NamaDisplay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        trLevel = new javax.swing.JTextField();
        trTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ajukan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        trSum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        trDesc = new javax.swing.JTextField();
        trPDate = new com.toedter.calendar.JDateChooser();
        Cancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        trID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        trReqDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        ReviewOffer.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        ReviewOffer.setText("Review Offers");
        ReviewOffer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReviewOffer.setContentAreaFilled(false);
        ReviewOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewOfferActionPerformed(evt);
            }
        });
        jPanel2.add(ReviewOffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 50));

        Tutorial.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        Tutorial.setText("Tutorial ");
        Tutorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tutorial.setContentAreaFilled(false);
        Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialActionPerformed(evt);
            }
        });
        jPanel2.add(Tutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 50));

        Resource.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        Resource.setText("Resource");
        Resource.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Resource.setContentAreaFilled(false);
        Resource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourceActionPerformed(evt);
            }
        });
        jPanel2.add(Resource, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 300, 50));

        LogOut.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogOut.setContentAreaFilled(false);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 300, 50));

        SchoolNameAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        SchoolNameAdmin.setText("jLabel6");
        jPanel2.add(SchoolNameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, 30));

        NameAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NameAdmin.setText("jLabel6");
        jPanel2.add(NameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 30));

        PositionAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        PositionAdmin.setText("jLabel6");
        jPanel2.add(PositionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 30));

        IdSchool.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        IdSchool.setText("jLabel6");
        jPanel2.add(IdSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 600));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/School[Dashboard].png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel2.setText(" School HELP");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 250, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/UserProfile.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 2, -1, 50));

        NamaDisplay.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NamaDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NamaDisplay.setText("jLabel4");
        jPanel3.add(NamaDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 300, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel7.setText("Proposed Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel10.setText("Student Level");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        trLevel.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(trLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 400, -1));

        trTime.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(trTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 400, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tutorial Request");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 900, 60));

        Ajukan.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        Ajukan.setText("Ajukan");
        Ajukan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ajukan.setContentAreaFilled(false);
        Ajukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjukanActionPerformed(evt);
            }
        });
        jPanel1.add(Ajukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 100, 30));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel11.setText("Sum of Student");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        trSum.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(trSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 400, -1));

        jLabel12.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel12.setText("Description");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        trDesc.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(trDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 400, -1));

        trPDate.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jPanel1.add(trPDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 400, 30));

        Cancel.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel.setContentAreaFilled(false);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 100, 30));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel9.setText("Request ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        trID.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jPanel1.add(trID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 400, -1));

        jLabel13.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel13.setText("Proposed Time");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bitstream Charter", 0, 20)); // NOI18N
        jLabel14.setText("Request Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        trReqDate.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jPanel1.add(trReqDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 400, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //fungsi untuk ke halaman review Offers
    private void ReviewOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewOfferActionPerformed
        // TODO add your handling code here:
        SchoolAdmin_3 sa3 = new SchoolAdmin_3();
        sa3.setVisible(true);
        sa3.Display(NamaDisplay.getText());
        sa3.DisplayInfo(NameAdmin.getText(), PositionAdmin.getText(), IdSchool.getText(), SchoolNameAdmin.getText());
        this.dispose();
    }//GEN-LAST:event_ReviewOfferActionPerformed

    //fugnsi untuk ke halaman resource request
    private void ResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourceActionPerformed
        // TODO add your handling code here:
        SchoolAdmin_2 sa = new SchoolAdmin_2();
        sa.setVisible(true);
        sa.DisplayInfo(NameAdmin.getText(), PositionAdmin.getText(), IdSchool.getText(), SchoolNameAdmin.getText());
        this.dispose();
    }//GEN-LAST:event_ResourceActionPerformed

    //fungsi untuk log outdan kembali ke halaman login
    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    //fungsi untuk merefresh halaman
    private void TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialActionPerformed
        // TODO add your handling code here:
        SchoolAdmin_1 sa1 = new SchoolAdmin_1();
        sa1.setVisible(true);
        sa1.Display(NamaDisplay.getText());
        sa1.DisplayInfo(NameAdmin.getText(), PositionAdmin.getText(), IdSchool.getText(), SchoolNameAdmin.getText());
        this.dispose();
    }//GEN-LAST:event_TutorialActionPerformed

    //fungsi untuk membatalkan request
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        trID.setText("");
        
        trReqDate.setDate(null);
        trPDate.setDate(null);
        trTime.setText("");
        trLevel.setText("");
        trSum.setText("");
        trDesc.setText("");
    }//GEN-LAST:event_CancelActionPerformed

    //fungsi untuk mengajukan request
    private void AjukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjukanActionPerformed
        // cek apakah data sudah terisi semua atau belum
        if (validateText()){
            //fungsi untuk memformat tanggal dan ngecash ke string
            SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
            String reqID = trID.getText().trim();
            String Status = "PENDING";
            String reqDate = dt.format(trReqDate.getDate());
            String PropDate = dt.format(trPDate.getDate());
            String Time = trTime.getText().trim();
            String Level = trLevel.getText().trim();
            String Sum = trSum.getText().trim();
            String Desc = trDesc.getText().trim();
            String Schoolname = SchoolNameAdmin.getText().trim();
            
            //panggil contructor tutorial
            Tutorial T = new Tutorial(Schoolname, PropDate, Time, Level, Sum, reqID, reqDate, Status , Desc);
            
            //data dari constructor disimpan ke dalam arraylist
            t.add(T);
            
            //data dari array list akan disimpan ke dalam file.dat
            savetoFile();
        }
        
    }//GEN-LAST:event_AjukanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolAdmin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolAdmin_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajukan;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel IdSchool;
    private javax.swing.JButton LogOut;
    private javax.swing.JLabel NamaDisplay;
    private javax.swing.JLabel NameAdmin;
    private javax.swing.JLabel PositionAdmin;
    private javax.swing.JButton Resource;
    private javax.swing.JButton ReviewOffer;
    private javax.swing.JLabel SchoolNameAdmin;
    private javax.swing.JButton Tutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField trDesc;
    private javax.swing.JTextField trID;
    private javax.swing.JTextField trLevel;
    private com.toedter.calendar.JDateChooser trPDate;
    private com.toedter.calendar.JDateChooser trReqDate;
    private javax.swing.JTextField trSum;
    private javax.swing.JTextField trTime;
    // End of variables declaration//GEN-END:variables
}
